name: Set version pushed by git tag into associated files

on:
  push:
    tags: "**"

jobs:
  version-updater:
    name: Insert version of git tag into files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag version v[0-9].[0-9].[0-9]
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Update version files
        run: |
          newVersionWithV='${{ steps.vars.outputs.tag }}'
          sed -i 's/\bv[0-9].[0-9].[0-9]\b/'"$newVersionWithV"'/g' EZGUI.lua

          newVersionWithoutV=$(cut -c 2-6 <<< $newVersionWithV)
          sed -i 's/"\b[0-9].[0-9].[0-9]\b"/'\"$newVersionWithoutV\"'/g' package.json

          sed -i 's/UNRELEASED/'$newVersionWithV'/g' changelog.txt

          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add EZGUI.lua
          git add package.json
          git add changelog.txt

          git commit -m "Update version files"
          git push
